# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190325_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_main',
        ),
    ]
