# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190305_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
