# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image_6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='Product', to='products.Categories'),
        ),
    ]
