# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190329_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category',
            new_name='name',
        ),
    ]
