# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-31 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190331_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_1',
            new_name='image_main',
        ),
    ]
